# recuperar pelicualas
//GET http://localhost:1234/movies

#obtener una pelicula por id
//GET  http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

#Recuperar pelicula por genero
//GET http://localhost:1234/movies?genre=Action

#crear pelicula

POST http://localhost:1234/movies

Content-Type: application/json
{
    "title":"werweInceptionfdfgf",
    "year":2010,
    "director":"weweChristopher Nolanfdgdf",
    "duration":1487,
    "genre":"Sci-Fi",
     "poster":"https://example.com/poster.jpg",
    "rating":8.8,
    "duration":148,
}


PATCH  http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json
{
    "year":2020
}